name: CI

on:
  push:

  schedule:
  - cron: "0 0 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Docker pull base image
      run: docker pull perl:5.30.0

    - name: Build docker image
      run: docker build . --tag tmp:${{ github.sha }}

    - name: Run test in t/
      run: docker run --rm --volume=`pwd`/lib/:/data/ tmp:${{ github.sha }} prove -l t/
